version: '3.8'
services:
  mongodb:
    image: 'mongo:5.0.15'
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

volumes:
  mongodb_data_container:

  #docker-compose up -d
